name: This is my first github workflow

on:
  push:
     branch: ["main"]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from github ${{ github.event_name }} event."
