name: Exploring Outputs In Github Actions

on:
  push:
    branch: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: setting output
        id: step1
        run:  echo "name=Browny" >> $GITHUB_OUTPUT
      - name: printing output from step1
        run: echo "name from previoud step is ${{steps.step1.outputs.name}}"